export const experiences = [
  {
    company: 'Tecna Sistemas Eireli',
    tag: 'tecna',
    position: 'Front End Developer',
    period: 'Março/2022 - Agosto/2023',
    initialRoleDescription:
      'Iniciei minha trajetória na Tecna em março de 2022, originalmente buscando uma posição de estagiário. No entanto, após o processo seletivo, fui contratado como Desenvolvedor Web Jr. em regime de Microempreendedor Individual (MEI) em um momento em que a empresa estava formando sua equipe de desenvolvimento.',
    responsibilities: [
      'Desenvolvimento de aplicativos web com integração de APIs.',
      'Levantamento de requisitos para projetos.',
      'Criação de mockups e layouts.',
      'Implementação de bots de atendimento.',
      'Desenvolvimento de aplicações Zendesk.',
      'Manutenção de sites WordPress.',
      'Controle de versionamento usando Git.',
      'Participação em reuniões com clientes.',
      'Colaboração ativa no ciclo de desenvolvimento.',
      'Testes e depuração de códigos.',
      'Otimização de aplicações para melhor experiência do usuário.',
      'Colaboração em equipes multidisciplinares.',
      'Pesquisa de novas tecnologias e tendências.',
      'Resolução de problemas técnicos e suporte.',
      'Documentação completa de códigos e processos.',
      'Integração de sistemas para interoperabilidade.',
      'Participação em revisões de código.',
      'Treinamento e capacitação de equipes.',
      'Acompanhamento de métricas e análise de dados.',
      'Colaboração em processos de melhoria contínua.',
    ],
    additionalExperienceText: [
      "Na Tecna, aprimorei minhas habilidades em JavaScript e SASS, tendo contato com sistemas de gerenciamento de ticket e APIS' rest.",
      'Participei ativamente do desenvolvimento de aplicativos integrados a APIs privadas e tive a oportunidade de gerir reuniões com clientes desde os primeiros dias de trabalho, com autonomia para conduzir levantamentos de requisitos, desenvolver mockups e tocar os projetos ao longo de todo o ciclo de desenvolvimento.',
      'Além disso, desempenhei um papel importante na criação de um sistema interno de gerenciamento de projetos utilizando o Notion, o qual substituiu a solução anteriormente usada. A ideia era termos maior visibilidade das demandas e progressos da equipe de desenvolvimento.',
      'Também atuei desenvolvendo bots eficientes para o Zendesk, proporcionando suporte automatizado de qualidade e adicionalmente executei correções e recriação do site da empresa em WordPress.',
      'Esta experiência enriquecedora contribuiu significativamente para meu crescimento profissional, aprimorando minhas habilidades técnicas e interpessoais em cenários reais.',
    ],
  },
  {
    company: 'Outlet Comércio de Materiais Eireli - ME',
    tag: 'outlet',
    position: 'Auxiliar de Licitações',
    period: 'Outubro/2017 – Outubro/2021',
    initialRoleDescription:
      'Iniciei minha jornada na Outlet Comércio de Materiais EIRELI - ME em outubro de 2017, ocupando o cargo de Auxiliar de Licitações. Durante o período até outubro de 2021, desempenhei diversas responsabilidades cruciais para o setor de licitações, demonstrando habilidades essenciais como atenção, organização, comunicação eficiente e trabalho em equipe.',
    responsibilities: [
      'Elaboração de orçamentos para participação em processos licitatórios.',
      'Cadastro da empresa em órgãos públicos e plataformas de licitações.',
      'Participação ativa em processos licitatórios, seguindo as diretrizes estabelecidas.',
      'Realização de operações de compra, venda e fornecimento de materiais.',
      'Controle minucioso de propostas, garantindo precisão e conformidade.',
      'Organização e arquivamento de atas e documentos de habilitação.',
      'Análise detalhada de editais e especificações técnicas para atender aos requisitos.',
      'Comunicação eficiente com órgãos públicos, fornecedores e demais partes envolvidas.',
      'Execução de atividades que demandam atenção meticulosa e organização.',
      'Trabalho colaborativo em equipe para cumprir prazos e metas estabelecidas em processos licitatórios.',
    ],
    additionalExperienceText: [
      'Minhas atividades abrangeram desde a elaboração de orçamentos até o cadastro e participação em processos licitatórios. Realizei operações relacionadas à compra, venda e fornecimento, garantindo conformidade com as propostas, atas, e documentos de habilitação. Destaco minha capacidade na análise aprofundada de editais e especificações técnicas, contribuindo para o êxito em diversas licitações.',
      'Estabeleci e mantive uma comunicação eficaz com órgãos públicos, consolidando parcerias e mantendo um fluxo de informações constante. Além disso, participei de outras atividades que demandaram habilidades específicas, sempre buscando aprimorar processos e garantir a excelência nas operações.',
      'Minha passagem pela Outlet Comércio de Materiais EIRELI - ME fortaleceu minhas competências em lidar com desafios complexos no contexto de licitações, e contribuiu para meu desenvolvimento profissional em um ambiente dinâmico e exigente.',
    ],
  },
  {
    company: 'CP Andrade Eletrônicos - ME',
    tag: 'cp',
    position: 'Auxiliar Técnico em Eletrônica',
    period: 'Março/2016 - Novembro/2017',
    initialRoleDescription:
      'Na CP Andrade Eletrônicos - ME, atuei como Auxiliar Técnico em Eletrônica de março de 2016 a novembro de 2017. Minhas responsabilidades abrangeram diversas áreas, incluindo atendimento ao público, controle de estoque e manutenção em hardware de dispositivos como telemóveis, computadores e outros eletrônicos.',

    responsibilities: [
      'Atendimento ao público, proporcionando suporte técnico e esclarecendo dúvidas.',
      'Controle eficiente de estoque de componentes eletrônicos e peças de reposição.',
      'Realização de manutenção em hardware de dispositivos, como telemóveis e computadores.',
      'Diagnóstico e solução de problemas em hardware de diversos eletrônicos.',
      'Recuperação de software em dispositivos móveis utilizando box CLI e adb.',
      'Execução de procedimentos de manutenção preventiva em equipamentos eletrônicos.',
      'Colaboração em processos de atualização de software para dispositivos móveis.',
      'Testes e avaliação de funcionalidades após a realização de reparos.',
      'Treinamento e orientação a clientes sobre o uso adequado de equipamentos.',
      'Trabalho em conformidade com padrões e normas técnicas do setor eletrônico.',
    ],
    additionalExperienceText: [
      'Durante minha estadia, desenvolvi habilidades na recuperação de software mobile, utilizando ferramentas como box CLI e adb. Minhas tarefas incluíram diagnóstico e solução de problemas técnicos, garantindo o pleno funcionamento dos dispositivos eletrônicos.',
      'Além disso, mantive um padrão de atendimento ao público que refletia profissionalismo e eficiência, contribuindo para a satisfação dos clientes. Minha experiência na CP Andrade Eletrônicos consolidou meu conhecimento técnico em eletrônica e proporcionou uma compreensão abrangente do ciclo de vida dos produtos eletrônicos.',
    ],
  },
];
